// Moves drizzle-kit pull output into src/schema and repairs known introspection
// defects (drizzle-kit 0.31 against this Prisma-created schema):
//   1. text DEFAULT ''                       -> emitted as `.default(')`  (unterminated)
//   2. double precision[] DEFAULT ARRAY[]::… -> emitted as `.default([RAY])`
//   3. casing:"camel" renames columns like `p256dh` -> `p256Dh` but omits the
//      explicit column name (no underscore), so `generate` sees a new column.
//      Fix: add the explicit DB column name whenever the camelCased prop differs.
// Idempotent: safe to run after every pull.
import { readFileSync, writeFileSync, renameSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const out = resolve("drizzle");
const dest = resolve("src/schema");
for (const name of ["schema.ts", "relations.ts"]) {
  const src = resolve(out, name);
  if (existsSync(src)) renameSync(src, resolve(dest, name));
}

const schemaPath = resolve(dest, "schema.ts");
let schema = readFileSync(schemaPath, "utf8");
const before = schema;

// 1 + 2: broken defaults
schema = schema.replace(/\.default\(\'\)/g, ".default('')");
schema = schema.replace(/\.default\(\[RAY\]\)/g, ".default([])");

// 3: implicit column names that no longer match the DB
const snapshots = existsSync(resolve(out, "meta"))
  ? (await import("node:fs")).readdirSync(resolve(out, "meta")).filter((f) => f.endsWith("_snapshot.json")).sort()
  : [];
if (snapshots.length > 0) {
  const snap = JSON.parse(readFileSync(resolve(out, "meta", snapshots[snapshots.length - 1]), "utf8"));
  const columnNames = new Set();
  for (const table of Object.values(snap.tables ?? {})) for (const col of Object.values(table.columns ?? {})) columnNames.add(col.name);
  schema = schema.replace(/^(\t)([A-Za-z_$][\w$]*): (\w+)\(\)/gm, (m, indent, prop, type) => {
    if (columnNames.has(prop)) return m;
    const lower = prop.toLowerCase();
    if (columnNames.has(lower)) return `${indent}${prop}: ${type}("${lower}")`;
    return m;
  });
}

if (!schema.startsWith("// GENERATED")) {
  schema =
    "// GENERATED by `pnpm --filter @nexora/db db:pull` (drizzle-kit pull + scripts/post-pull.mjs).\n" +
    "// Do not hand-edit except through post-pull.mjs; hand-written tables live in auth.ts.\n" +
    schema;
}
if (schema !== before) writeFileSync(schemaPath, schema);

const relPath = resolve(dest, "relations.ts");
// Read directly and handle ENOENT rather than existsSync-then-read, avoiding a
// check-then-act TOCTOU (CodeQL js/file-system-race).
try {
  const rel = readFileSync(relPath, "utf8");
  if (!rel.startsWith("// GENERATED")) writeFileSync(relPath, "// GENERATED by `pnpm --filter @nexora/db db:pull`. Do not hand-edit.\n" + rel);
} catch (err) {
  if (err.code !== "ENOENT") throw err;
}
console.log("post-pull: schema.ts + relations.ts in src/schema (defaults + implicit column names repaired)");
